# Site settings
title: Mikael Melander
email: mm222ev@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Examination of course 1DV022 at Linneuniversitetet
  My name is Mikael Melander.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  Melanderm

# Build settings
markdown: kramdown
